// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA71u4Rot8DXhSjyb6EzfagBYm5udkIFY',
    appId: '1:333915198544:web:8cec316a549ab2d1da2d55',
    messagingSenderId: '333915198544',
    projectId: 'dog-friends-2023',
    authDomain: 'dog-friends-2023.firebaseapp.com',
    storageBucket: 'dog-friends-2023.appspot.com',
    measurementId: 'G-V73L2XMPRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFiMXNjPrHnoCCIePcomrnxGfwKiKMzAo',
    appId: '1:333915198544:android:58b6b668bab9af16da2d55',
    messagingSenderId: '333915198544',
    projectId: 'dog-friends-2023',
    storageBucket: 'dog-friends-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxhT81lkNt0ZPQ4fH0fzUjJovXzOz0v8I',
    appId: '1:333915198544:ios:bc52c3698b27dca9da2d55',
    messagingSenderId: '333915198544',
    projectId: 'dog-friends-2023',
    storageBucket: 'dog-friends-2023.appspot.com',
    iosBundleId: 'com.example.dogFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxhT81lkNt0ZPQ4fH0fzUjJovXzOz0v8I',
    appId: '1:333915198544:ios:929cc43815a755b2da2d55',
    messagingSenderId: '333915198544',
    projectId: 'dog-friends-2023',
    storageBucket: 'dog-friends-2023.appspot.com',
    iosBundleId: 'com.example.dogFriends.RunnerTests',
  );
}
