import 'dog_model.dart';

List<DogModel> dogsList = [
  DogModel(
    name: "Tokyo",
    breed: "Metis husky",
    gender: "Female",
    birthDate: "21.04.2022",
    dogFeatures: "Average height. Sterilized",
    image: "assets/images/tokyo1.jpeg",
  ),
  DogModel(
    name: "Bublyk",
    breed: "Metis",
    gender: "Male",
    birthDate: "20.05.2022",
    dogFeatures: "Average height. Emasculate",
    image: "assets/images/bublyk.jpeg",
  ),
  DogModel(
    name: "Disney",
    breed: "Mini dachshund",
    gender: "Female",
    birthDate: "30.05.2022",
    dogFeatures: "Average height. Not sterilized",
    image: "assets/images/disney.jpeg",
  ),
  DogModel(
    name: "Javelina",
    breed: "Black shepherd",
    gender: "Female",
    birthDate: "15.02.2022",
    dogFeatures: "Average height. Not sterilized",
    image: "assets/images/javelina.jpeg",
  ),
  DogModel(
    name: "Rocket",
    breed: "Metis dachshund",
    gender: "Female",
    birthDate: "12.01.2021",
    dogFeatures: "Small height. Sterilized",
    image: "assets/images/rocket.jpeg",
  ),
  DogModel(
    name: "Happy",
    breed: "Metis",
    gender: "Female",
    birthDate: "30.05.2022",
    dogFeatures: "Average height. Not sterilized",
    image: "assets/images/happy.jpeg",
  ),
  DogModel(
    name: "Baks",
    breed: "Am. Bully",
    gender: "Male",
    birthDate: "11.05.2023",
    dogFeatures: "Average height. Not sterilized",
    image: "assets/images/baks.jpeg",
  ),
  DogModel(
    name: "Feona",
    breed: "Husky",
    gender: "Female",
    birthDate: "03.09.2023",
    dogFeatures: "Average height. Not sterilized",
    image: "assets/images/husky.jpeg",
  ),
];
